Loadtesting
Informatievlaanderen/registry-testing pull request #1
Opened 2019-10-28 08:36 UTC by ridingwolf

2019-11-28 16:34 UTC, ridingwolf commented
todo:
- add the filtered lists for all registries
- add addressmatch
- review the distribution of calls per registry 
- review the distribution of calls to registries (weight set in `ApiSimulation.scala`)

2019-12-12 09:52 UTC, CumpsD requested changes
Place some stuff in vars please

2019-12-12 09:52 UTC, CumpsD commented on user-files/simulations/infrastructure/RegistrySimulation.scala
> +  private val loadTestApiKey = "REPLACEME"
Get this from vars

2019-12-12 09:52 UTC, CumpsD commented on user-files/simulations/infrastructure/RegistrySimulation.scala
> +    .baseUrl("https://api.basisregisters.vlaanderen/v1")
Get this from vars

2019-12-12 09:52 UTC, CumpsD commented on user-files/simulations/infrastructure/RegistrySimulation.scala
> +    .warmUp("https://www.vlaanderen.be/nl")
Get this from vars. `https://api.basisregisters.vlaanderen/v1/versions`

2019-12-12 11:54 UTC, merged